language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  - FLASK_VERSION=0.9
  - FLASK_VERSION=0.10.1
  - FLASK_VERSION=0.11.1

matrix:
  exclude:
    - python: 3.3
      env: FLASK_VERSION=0.9
    - python: 3.4
      env: FLASK_VERSION=0.9
    - python: 3.5
      env: FLASK_VERSION=0.9

install:
  - pip install -q Flask==$FLASK_VERSION
  - pip install -q pep8 pyflakes
  - pip install -q .

before_script:
  - pep8 flask_xuanzang
  - pyflakes flask_xuanzang

script:
  - nosetests
